V4 docstrings
magpylib/magpylib pull request #479
Opened 2022-02-22 21:22 UTC by OrtnerMichael

# Related Issues
#419 
#412 first steps only
#406 done
#403 code tasks

# Notes
- new input checks with properly formatted error messages
- `checkinputs` parameter is completely out, input checks are always performed
- not more tool tip codes `dimension=(a,b,c)` but only `dimension=None` inits
- complete docstings of V4 codes
- some minor code refactorings and mini-bugfixes

2022-02-22 21:24 UTC, Alexboiboi commented
squash or merge. I'd squash

2022-02-22 23:05 UTC, Alexboiboi requested changes

2022-02-22 23:05 UTC, Alexboiboi commented on magpylib/_src/utility.py
> +                dims=(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20),
What is this???

2022-02-23 07:12 UTC, OrtnerMichael commented on magpylib/_src/display/display.py
> +    backend = check_format_input_backend(backend)
I think we should have completely separate input checks where good and bad inputs are defined. I already made this an issue #406 .

Also I did not see an else statement in the `show` function.

2022-02-23 07:15 UTC, OrtnerMichael commented on magpylib/_src/display/display.py
> +    backend = check_format_input_backend(backend)
ah ... this did not exist when I forked off.

2022-02-23 07:27 UTC, OrtnerMichael commented on magpylib/_src/display/display.py
> +    backend = check_format_input_backend(backend)
fixed as proposed with new commit

2022-02-23 07:54 UTC, OrtnerMichael commented on magpylib/_src/display/display.py
> +    check_input_animation(animation)
fixed as above

2022-02-23 08:00 UTC, OrtnerMichael commented on magpylib/_src/input_checks.py
> +    if not (isinstance(inp, (int, np.int_)) or inp == 'auto'):
fixed

2022-02-23 08:05 UTC, OrtnerMichael commented on magpylib/_src/input_checks.py
> +    if not (isinstance(inp, (int, np.int_)) or inp == 'auto'):
done

2022-02-23 08:06 UTC, OrtnerMichael commented on magpylib/_src/input_checks.py
> +    if not isinstance(inp, (bool, float, int, np.float_, np.int_)):
fixed

2022-02-23 09:58 UTC, Alexboiboi approved these changes

2022-02-23 10:00 UTC, merged